[unix_http_server]
file=/root/autodl-tmp/xiaozhi-autodl/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/root/autodl-tmp/xiaozhi-autodl/logs/supervisord.log
pidfile=/root/autodl-tmp/xiaozhi-autodl/run/supervisord.pid
childlogdir=/root/autodl-tmp/xiaozhi-autodl/logs
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///root/autodl-tmp/xiaozhi-autodl/run/supervisor.sock

[include]
files=/root/xiaozhi-autodl/config/supervisor/programs.d/*.conf
